# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.3 on 2026-03-13 05:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("django_regional", "0006_country_default_currency")]

    operations = [
        migrations.CreateModel(
            name="AgreementDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("slug", models.CharField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("mandatory", "Mandatory"),
                            ("marketing", "Marketing"),
                            ("informational", "Informational"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "consent_channel",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push"),
                            ("web", "Web"),
                        ],
                        default="general",
                        max_length=10,
                    ),
                ),
                ("content_route", models.CharField(blank=True, default="", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="System consents are fixture-managed and cannot be deleted via CMS"
                    ),
                ),
                (
                    "display_contexts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Where this consent appears: ["checkout", "registration", "newsletter"]',
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.CreateModel(
            name="AgreementVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("version_number", models.PositiveIntegerField()),
                (
                    "summary_t9n",
                    models.JSONField(
                        default=dict,
                        help_text='Checkbox label per language: {"en": "I accept...", "pl": "Akceptuję..."}',
                    ),
                ),
                (
                    "content_published_id",
                    models.IntegerField(
                        blank=True, help_text="Soft reference to ContentDB Published.pk (full legal text)", null=True
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, help_text="Null = draft, set = live", null=True)),
                (
                    "is_current",
                    models.BooleanField(default=False, help_text="One True per definition — enforced by service layer"),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="django_agreements.agreementdefinition",
                    ),
                ),
            ],
            options={"ordering": ["-version_number"]},
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("idx", models.CharField(max_length=128, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                (
                    "default_language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agreements_default_channels",
                        to="django_regional.language",
                    ),
                ),
                (
                    "languages",
                    models.ManyToManyField(
                        blank=True, related_name="agreements_channels", to="django_regional.language"
                    ),
                ),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="agreementdefinition",
            name="channels",
            field=models.ManyToManyField(blank=True, related_name="definitions", to="django_agreements.channel"),
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "customer_id",
                    models.IntegerField(
                        blank=True, help_text="Soft reference to customer account (no FK to django-accounts)", null=True
                    ),
                ),
                ("granted", models.BooleanField(help_text="True=consent given, False=withdrawn")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("checkout", "Checkout"),
                            ("registration", "Registration"),
                            ("consent-page", "Consent Page"),
                            ("newsletter-signup", "Newsletter Signup"),
                            ("api", "API"),
                            ("import", "Import"),
                            ("crm-v1", "CRM v1 Bridge"),
                            ("double-optin-pending", "Double Opt-In Pending"),
                            ("double-optin-confirmed", "Double Opt-In Confirmed"),
                            ("unsubscribed", "Unsubscribed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                (
                    "channel_idx",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Which channel this consent was given in (audit trail)",
                        max_length=128,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agreement_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consent_records",
                        to="django_agreements.agreementversion",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="OrderAgreementSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "order_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, help_text="Matches Order.order_id (no FK to django-checkout)"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "body_snapshot",
                    models.TextField(help_text="Full legal text at acceptance time (denormalized from ContentDB)"),
                ),
                ("language", models.CharField(help_text="Language version shown to customer (iso2)", max_length=5)),
                ("granted", models.BooleanField(default=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agreement_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_snapshots",
                        to="django_agreements.agreementversion",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="agreementversion",
            constraint=models.UniqueConstraint(
                fields=("definition", "version_number"), name="unique_definition_version"
            ),
        ),
        migrations.AddIndex(
            model_name="consentrecord",
            index=models.Index(fields=["email", "-created_at"], name="idx_consent_email_date"),
        ),
        migrations.AddConstraint(
            model_name="orderagreementsnapshot",
            constraint=models.UniqueConstraint(
                fields=("order_id", "agreement_version"), name="unique_order_agreement_version"
            ),
        ),
    ]
