# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.7 on 2026-09-13 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_agreements", "0001_initial"),
        ("django_regional", "0006_country_default_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClauseSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "legal_basis",
                    models.CharField(
                        choices=[
                            ("consent", "Consent (art. 6(1)(a))"),
                            ("legitimate_interest", "Legitimate interest (art. 6(1)(f))"),
                            ("contract", "Contract (art. 6(1)(b))"),
                        ],
                        max_length=32,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("info_clause", models.TextField()),
                ("optout_clause", models.TextField()),
                ("retention_clause", models.TextField()),
                (
                    "is_current",
                    models.BooleanField(default=False, help_text="One True per triple — enforced by service layer"),
                ),
                ("published_at", models.DateTimeField(blank=True, help_text="Null = draft, set = live", null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clause_sets",
                        to="django_agreements.channel",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agreements_clause_sets",
                        to="django_regional.language",
                    ),
                ),
            ],
            options={
                "ordering": ["channel", "legal_basis", "language", "-version"],
            },
        ),
        migrations.CreateModel(
            name="ObjectionEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "source",
                    models.CharField(
                        choices=[("communicator", "Communicator"), ("manual", "Manual"), ("api", "API")], max_length=32
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="objection_events",
                        to="django_agreements.channel",
                    ),
                ),
                (
                    "clause_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="objection_events",
                        to="django_agreements.clauseset",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="clauseset",
            constraint=models.UniqueConstraint(
                fields=("channel", "legal_basis", "language", "version"), name="unique_clause_set_version"
            ),
        ),
    ]
