# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.7 on 2026-09-24 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_agreements", "0003_objection_clause_set_protect"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreementversion",
            name="cookie_banner",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Cookie banner config (categories, buttons) — only for category=cookies",
            ),
        ),
        migrations.AlterField(
            model_name="agreementdefinition",
            name="category",
            field=models.CharField(
                choices=[
                    ("mandatory", "Mandatory"),
                    ("marketing", "Marketing"),
                    ("informational", "Informational"),
                    ("cookies", "Cookies"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CookieConsent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("consent_id", models.UUIDField(help_text="Random id the banner keeps in a first-party cookie")),
                ("channel_idx", models.CharField(max_length=128)),
                ("language", models.CharField(help_text="ISO 639-1 code the banner was shown in", max_length=2)),
                (
                    "categories",
                    models.JSONField(help_text='Decision per category: {"analytics": true, "marketing": false}'),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("accept_all", "Accept all"),
                            ("reject_all", "Reject all"),
                            ("custom", "Custom"),
                            ("withdraw", "Withdraw"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agreement_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cookie_consents",
                        to="django_agreements.agreementversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["consent_id", "-created_at"], name="idx_cookie_consent_id_date"),
                    models.Index(fields=["channel_idx", "created_at"], name="idx_cookie_channel_date"),
                    models.Index(fields=["created_at"], name="idx_cookie_created"),
                ],
            },
        ),
    ]
